baseURL: "https://andriamirado.org" 
title: Manoa Andriamirado
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2

params:
    description: "I'm a 5th year Ph.D. student in experimental particle physics at Illinois institute of Technology."
    author: Manoa Andriamirado
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Manoa Andriamirado
          subtitle: "Hello! Welcome to my website!
          
            <br> <br>
            My name is Manoa Andriamirado, a 5th year Ph.D. student in experimental particle physics at the  Illinois Institute
            of Technology. I am working at the PROSPECT reactor antineutrino experiment under the supervision of Prof. Bryce Littlejohn.
    
            <br> <br>
            My current research expertise gravitates around sterile neutrinos and nuclear physics. Specifically, I use inverse 
            beta decay interactions from antineutrinos originating at a research nuclear reactor as a probe for a potential 
            fourth neutrino flavor, called the sterile neutrino. Sterile neutrinos in the eV$^2$ mass splitting range have been
            hypothesized as a possible cause of a phenomenon known as Reactor Antineutrino Anomaly (RAA), which consists of a 
            disagreement between measurement and the prediction of the antineutrino flux from reactors. More generally, 
            reactor-based experiments are the best existing probes of electron neutrino disappearance and are thus an essential
            component in a global effort to understand anomalous short-baseline neutrino measurements."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Manoa Andriamirado
          buttons:
            - name: Publications
              url: publications/
            - name: Projects
              url: projects/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:manoa.andriamirado@gmail.com
        - name: INSPIRES-HEP
          url: https://inspirehep.net/authors/1684084
        - name: GitHub
          url: https://github.com/mandri97

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "M. Andriamirado"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
